# Generated by Django 6.0.2 on 2026-03-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('calories', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('fiber', models.FloatField(default=0)),
                ('vitamin_a', models.FloatField(default=0)),
                ('vitamin_c', models.FloatField(default=0)),
                ('calcium', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('potassium', models.FloatField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='ingredients_slug_97bd95_idx')],
            },
        ),
        migrations.CreateModel(
            name='IngredientBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='ingredients.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ingredients/')),
                ('video_url', models.URLField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ingredients.ingredient')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IngredientWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='ingredients.ingredient')),
            ],
        ),
    ]
