# Generated by Django 6.0.2 on 2026-03-03 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_image_articles_goal_image_products_and_more'),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='buy_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='IngredientGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_text', models.CharField(max_length=255)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_links', to='goals.goal')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_links', to='ingredients.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'goal')},
            },
        ),
    ]
