# Generated by Django 6.0.2 on 2026-03-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_buy_url_ingredientgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientwarning',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='calcium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='iron',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='potassium',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='vitamin_a',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='vitamin_c',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('nuts_and_seeds', 'Nuts & Seeds'), ('fruits', 'Fruits'), ('vegetables', 'Leafy Greens & Vegetables'), ('meats_and_animal_products', 'Meats & Animal Products'), ('grains_and_legumes', 'Grains & Legumes'), ('herbs_and_spices', 'Herbs & Spices')], db_index=True, default='nuts_and_seeds', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientgoal',
            name='benefit_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='IngredientMicronutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micronutrients', to='ingredients.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientMineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent_dv', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minerals', to='ingredients.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientVitamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('percent_dv', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitamins', to='ingredients.ingredient')),
            ],
        ),
        migrations.DeleteModel(
            name='IngredientBenefit',
        ),
        migrations.DeleteModel(
            name='IngredientWarning',
        ),
    ]
