# Generated by Django 6.0.2 on 2026-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_remove_ingredientwarning_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientgoal',
            name='scientific_explanation',
            field=models.TextField(blank=True, help_text='AI-generated scientific reason for this benefit'),
        ),
        migrations.AddField(
            model_name='ingredientgoal',
            name='usage_tips',
            field=models.TextField(blank=True, help_text='Practical tips for using this ingredient for this goal'),
        ),
    ]
