# Generated by Django 6.0.2 on 2026-03-03 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_goal_image_articles_goal_image_products_and_more'),
        ('recipes', '0004_recipe_meal_time_recipe_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('meals_per_day', models.PositiveIntegerField(default=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='goals.goal')),
            ],
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=1)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal_plans.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_items', to='recipes.recipe')),
            ],
            options={
                'ordering': ['day', 'meal_type', 'order'],
                'indexes': [models.Index(fields=['meal_plan', 'day', 'meal_type'], name='meal_plans__meal_pl_3461d9_idx')],
                'unique_together': {('meal_plan', 'day', 'meal_type', 'recipe')},
            },
        ),
    ]
