# Generated by Django 6.0.2 on 2026-03-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='goals/')),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='goals_goal_slug_b51549_idx')],
            },
        ),
    ]
