# Generated by Django 6.0.2 on 2026-03-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='image_articles',
            field=models.ImageField(blank=True, null=True, upload_to='goals/images/articles/'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image_products',
            field=models.ImageField(blank=True, null=True, upload_to='goals/images/products/'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image_recipes',
            field=models.ImageField(blank=True, null=True, upload_to='goals/images/recipes/'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image_workouts',
            field=models.ImageField(blank=True, null=True, upload_to='goals/images/workouts/'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='goals/images'),
        ),
    ]
