# Generated by Django 6.0.2 on 2026-03-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_image_articles_goal_image_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='image_workouts',
        ),
    ]
