# Generated by Django 6.0.2 on 2026-03-01 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articlecomment',
            index=models.Index(fields=['article', 'created_at'], name='articles_ar_article_59e165_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together={('article', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='articlereview',
            unique_together={('article', 'user')},
        ),
    ]
