'''
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
'''

from datetime import timedelta
from os import getenv
import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from local .env if present.
load_dotenv(BASE_DIR / '.env', override=False)

def env_bool(name: str, default: str = 'False') -> bool:
    return getenv(name, default).lower() in ('true', '1', 'yes')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv('SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG')

# Allow all hosts that are required
ALLOWED_HOSTS = [ 
    i.strip() 
    for i in getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') 
    if i.strip()
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users.apps.UsersConfig',
    'goals.apps.GoalsConfig',
    'ingredients.apps.IngredientsConfig',
    'recipes.apps.RecipesConfig',
    'meal_plans.apps.MealPlansConfig',
    'products.apps.ProductsConfig',
    'articles.apps.ArticlesConfig',
    'rag.apps.RagConfig',
    
    'pgvector.django',
    'rest_framework',
    'djoser',
    'social_django',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'import_export',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': getenv('DB_NAME'),
        'USER': getenv('DB_USER'),
        'PASSWORD': getenv('DB_PASSWORD'),
        'HOST': getenv('DB_HOST'),
        'PORT': getenv('DB_PORT'),
        'CONN_MAX_AGE': int(getenv('DB_CONN_MAX_AGE', '60')),
        'OPTIONS': {
            'sslmode': getenv('DB_SSLMODE', 'prefer')
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
if DEBUG:
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'static'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',   
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        }
    }

# Rest framework basic settings like authentication or permissions
# https://www.django-rest-framework.org/ 
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.auth.CustomJWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 15,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '2000/day',
        'anon': '200/day',
    },
}

# Simple JWT settings for Auth system
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/ 
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('JWT',),
}

# MailGun Setup
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', 'True')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'Teja Wellness <onboarding@resend.dev>')
EMAIL_TIMEOUT = 10

# Djoser Auth Library settings
# https://djoser.readthedocs.io/en/latest/index.html
REDIRECT_URLS = [
    u.strip() 
    for u in getenv('REDIRECT_URLS', '').split(',') 
    if u.strip()
]
DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': os.getenv('PASSWORD_RESET_CONFIRM_URL'),
    'USERNAME_RESET_CONFIRM_URL': os.getenv('USERNAME_RESET_CONFIRM_URL'),
    'EMAIL_FRONTEND_DOMAIN': os.getenv('EMAIL_FRONTEND_DOMAIN'),
    'EMAIL_FRONTEND_SITE_NAME': os.getenv('EMAIL_FRONTEND_SITE_NAME'),
    'SEND_ACTIVATION_EMAIL': env_bool('SEND_ACTIVATION_EMAIL'),
    'SEND_CONFIRMATION_EMAIL': env_bool('SEND_CONFIRMATION_EMAIL'),
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': env_bool('PASSWORD_CHANGED_EMAIL_CONFIRMATION'),
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': env_bool('USERNAME_CHANGED_EMAIL_CONFIRMATION'),
    'ACTIVATION_URL': os.getenv('ACTIVATION_URL'),
    'USER_CREATE_PASSWORD_RETYPE': env_bool('USER_CREATE_PASSWORD_RETYPE'),
    'SET_PASSWORD_RETYPE': env_bool('SET_PASSWORD_RETYPE'),
    'SET_USERNAME_RETYPE': env_bool('SET_USERNAME_RETYPE'),
    'PASSWORD_RESET_CONFIRM_RETYPE': env_bool('PASSWORD_RESET_CONFIRM_RETYPE'),
    'USERNAME_RESET_CONFIRM_RETYPE': env_bool('USERNAME_RESET_CONFIRM_RETYPE'),
    'TOKEN_MODEL': None,
    'SERIALIZERS': {
        'user': 'users.serializers.UserSerializer',
        'current_user': 'users.serializers.UserSerializer',
        'user_create': 'users.serializers.UserCreateSerializer',
        'user_create_password_retype': 'users.serializers.UserCreateSerializer',
    },
    'EMAIL': {
        'activation': 'users.emails.CustomActivationEmail',
        'confirmation': 'users.emails.CustomConfirmationEmail',
        'password_reset': 'users.emails.CustomPasswordResetEmail',
        'password_changed_confirmation': 'users.emails.CustomPasswordChangedConfirmationEmail',
        'username_changed_confirmation': 'users.emails.CustomUsernameChangedConfirmationEmail',
        'username_reset': 'users.emails.CustomUsernameResetEmail',
    },
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': REDIRECT_URLS,
}

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_AUTH_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_AUTH_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid'
]
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = { 'prompt': 'select_account' }
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['first_name', 'last_name']

# Authentication backends for both social auth and default model backend.
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Django CORS settings for allowed hosts
# https://pypi.org/project/django-cors-headers/
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in getenv(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000',
    ).split(',') if o.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

AUTH_COOKIE_ACCESS = os.getenv('AUTH_COOKIE_ACCESS', 'access')
AUTH_COOKIE_REFRESH = os.getenv('AUTH_COOKIE_REFRESH', 'refresh')
AUTH_COOKIE_SAMESITE = os.getenv('AUTH_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'Lax')
AUTH_COOKIE_SECURE = env_bool('AUTH_COOKIE_SECURE')
AUTH_COOKIE_HTTP_ONLY = True
AUTH_COOKIE_ACCESS_MAX_AGE = int(os.getenv('AUTH_COOKIE_ACCESS_MAX_AGE', '600'))
AUTH_COOKIE_REFRESH_MAX_AGE = int(os.getenv('AUTH_COOKIE_REFRESH_MAX_AGE', '1209600'))
AUTH_COOKIE_REFRESH_MAX_AGE_REMEMBER = int(os.getenv('AUTH_COOKIE_REFRESH_MAX_AGE_REMEMBER', '2592000'))
AUTH_COOKIE_PATH = '/'

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'fmt': '%(asctime)s %(levelname)s %(name)s %(message)s %(process)d %(thread)d',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(BASE_DIR / 'logs' / 'app.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        }
    }
}

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_BROWSER_XSS_FILTER = env_bool('SECURE_BROWSER_XSS_FILTER')
SECURE_CONTENT_TYPE_NOSNIFF = env_bool('SECURE_CONTENT_TYPE_NOSNIFF')
SECURE_REFERRER_POLICY = os.getenv(
    'SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
CSRF_TRUSTED_ORIGINS = [
    o.strip() 
    for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') 
    if o.strip()
]
CSRF_COOKIE_HTTPONLY = False

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.UserAccount'
