# Generated by Django 6.0.2 on 2026-03-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_diet_type_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
