# Generated by Django 6.0.2 on 2026-03-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(blank=True, choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combination', 'Combination'), ('sensitive', 'Sensitive'), ('normal', 'Normal')], max_length=20)),
                ('hair_type', models.CharField(blank=True, choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], max_length=20)),
                ('hair_texture', models.CharField(blank=True, choices=[('fine', 'Fine'), ('medium', 'Medium'), ('thick', 'Thick')], max_length=20)),
                ('skin_concerns', models.TextField(blank=True, help_text='Specific skin concerns')),
                ('hair_concerns', models.TextField(blank=True, help_text='Specific hair concerns')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
